#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

login_check:
  path:     /login_check
  methods:  POST

login:
  path: /login
  controller: App\Controller\AuthController::login

getUser:
  path: api/user
  controller: App\Controller\AuthController::receiveUser
  methods:  GET

updateUser:
  path: api/user
  controller: App\Controller\AuthController::updateUser
  methods:  POST