# phpmyadmin for admin database
'phpmyadmin':
  image: 'nazarpc/phpmyadmin:latest'
  container_name: 'phpmyadmin'
  environment:
  - ALLOW_ARBITRARY=1
  - URL=phpmyadmin.blog
  restart: always
  links: ['mysql_base','mysql_auth','mysql_finance']
  ports: ['30000:80']


##########################################
# Service `base`
##########################################
'php_base':
  build: ./php
  container_name: 'php_base'
  links: ['nginx_finance','nginx_auth','mysql_base']
  volumes: [ '../base:/var/www/html:cached' ]

'nginx_base':
  build: ./web
  container_name: 'nginx_base'
  links: ['php_base']
  volumes: [
    '../base:/var/www/html:cached',
    '../base/nginx.conf:/etc/nginx/conf.d/default.conf:cached'
  ]

  ports: ['8011:80']

'mysql_base':
  image: 'mysql:5.6.26'
  container_name: 'mysql_base'
  environment:
  - MYSQL_USER=root
  - MYSQL_ROOT_PASSWORD=root
  volumes: [/var/lib/mysql]
##########################################
# Service `auth`
##########################################
'php_auth':
  build: ./php
  container_name: 'php_auth'
  links: ['mysql_auth']
  volumes: [ '../auth:/var/www/html:cached' ]

'nginx_auth':
  build: ./web
  container_name: 'nginx_auth'
  links: ['php_auth']
  volumes: [
    '../auth:/var/www/html:cached',
    '../auth/nginx.conf:/etc/nginx/conf.d/default.conf:cached'
  ]

  ports: ['8311:80']

'mysql_auth':
  image: 'mysql:5.6.26'
  container_name: 'mysql_auth'
  environment:
  - MYSQL_USER=root
  - MYSQL_ROOT_PASSWORD=root
  volumes: [/var/lib/mysql]

##########################################
# Service `finance`
##########################################
'php_finance':
  build: ./php
  container_name: 'php_finance'
  links: ['mysql_finance']
  volumes: [
    '../finance:/var/www/html:cached',
  ]

'nginx_finance':
  build: ./web
  container_name: 'nginx_finance'
  links: ['php_finance']
  volumes: [
    '../finance:/var/www/html:cached',
    '../finance/nginx.conf:/etc/nginx/conf.d/default.conf:cached'
  ]

  ports: ['8322:80']

'mysql_finance':
  image: 'mysql:5.6.26'
  container_name: 'mysql_finance'
  environment:
  - MYSQL_USER=root
  - MYSQL_ROOT_PASSWORD=root
  volumes: [/var/lib/mysql]